#!/bin/bash

#
# The MIT License
#
# Copyright (c) 2020 Temporal Technologies Inc.  All rights reserved.
#
# Copyright (c) 2020 Uber Technologies, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

echo
echo " * Bringing services up, (re)building as required..."
echo

docker compose up --build -d

echo
echo " * Checking for custom search attributes..."
echo

until docker compose exec tools tctl --auto_confirm admin cluster add-search-attributes --name CandidateEmail --type keyword; do 
    echo "Waiting for Temporal Frontend to be up"
    sleep 1
done

until docker compose exec tools tctl --auto_confirm admin cluster add-search-attributes --name BackgroundCheckStatus --type keyword; do
    echo "Waiting for Temporal Frontend to be up"
    sleep 1
done

echo
echo " * All services are up"
echo

echo
echo " * The Background Check application is now running."
echo
echo "The following URLs are available to explore the sytem:"
echo
echo -e "\tTemporal Web:"
echo -e "\t\thttp://localhost:8088/data-converter/8086"
echo -e "\tMail Server (mailhog):"
echo -e "\t\thttp://localhost:8025/"
echo -e "\tGrafana:"
echo -e "\t\thttp://localhost:8085/"
echo
echo "You can check the logs for various components:"
echo
echo -e "docker compose logs worker"
echo -e "docker compose logs api"
echo -e "docker compose logs temporal"