#!/bin/bash

echo
echo " * Bringing services up, (re)building as required..."
echo

docker compose up --build -d

echo
echo " * Checking for custom search attributes..."
echo

until docker compose exec temporal-admin-tools tctl admin cluster add-search-attributes --name CandidateEmail --type Text > /dev/null 2>&1 ; do 
    echo "Waiting for Temporal Frontend to be up"
    sleep 1
done

until docker compose exec temporal-admin-tools tctl admin cluster add-search-attributes --name BackgroundCheckStatus --type keyword > /dev/null 2>&1 ; do
    echo "Waiting for Temporal Frontend to be up"
    sleep 1
done

echo
echo " * Ensuring all services are running (the worker may have died if Temporal wasn't quite ready yet...)"
echo

docker compose up --build -d

echo
echo " * All services are up"
echo

echo
echo " * The Background Check application is now running."
echo
echo "The following URLs are available to explore the sytem:"
echo
echo -e "\tTemporal Web:"
echo -e "\t\thttp://localhost:8088/"
echo -e "\tMail Server (mailhog):"
echo -e "\t\thttp://localhost:8025/"
echo -e "\tGrafana:"
echo -e "\t\thttp://localhost:8085/"