#!/bin/bash

echo
echo " * Bringing services up, (re)building as required..."
echo

docker compose up --build -d

echo
echo " * Checking for custom search attributes..."
echo

until docker compose exec tools tctl --auto_confirm admin cluster add-search-attributes --name CandidateEmail --type keyword; do 
    echo "Waiting for Temporal Frontend to be up"
    sleep 1
done

until docker compose exec tools tctl --auto_confirm admin cluster add-search-attributes --name BackgroundCheckStatus --type keyword; do
    echo "Waiting for Temporal Frontend to be up"
    sleep 1
done

echo
echo " * All services are up"
echo

urlencode() {
    old_lc_collate=$LC_COLLATE
    LC_COLLATE=C

    local length="${#1}"
    for (( i = 0; i < length; i++ )); do
        local c="${1:$i:1}"
        case $c in
            [a-zA-Z0-9.~_-]) printf '%s' "$c" ;;
            *) printf '%%%02X' "'$c" ;;
        esac
    done

    LC_COLLATE=$old_lc_collate
}

echo
echo " * The Background Check application is now running."
echo
echo "The following URLs are available to explore the sytem:"
echo
echo -e "\tTemporal Web:"
echo -e "\t\thttp://localhost:8080/remote-data-encoder/$(urlencode http://localhost:8081)"
echo -e "\tMail Server (mailhog):"
echo -e "\t\thttp://localhost:8025/"
echo -e "\tGrafana:"
echo -e "\t\thttp://localhost:8085/"
echo
echo "You can check the logs for various components:"
echo
echo -e "docker compose logs worker"
echo -e "docker compose logs api"
echo -e "docker compose logs temporal"
