{
 "title": "SDK",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(service_requests,cluster)"
    }
   },
   {
    "name": "Namespace",
    "query": "canary,benchtest,temporal_system"
   },
   { "name": "WorkflowType", "query": "cronWorkflow,workflow_sanity" }
  ]
 },
 "panels": [
  {
   "title": "RPC Overview ($Namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Vs Failures",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(temporal_request{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "requests"
      },
      {
       "expr": "sum(rate(temporal_request_failure{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "failures"
      }
     ]
    },
    {
     "title": "RPC Requests Per Operation",
     "type": "graph",
     "gridPos": { "h": 10, "w": 7, "x": 8, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) ((rate(temporal_request{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m])))",
       "legendFormat": "{{ operation }}"
      }
     ]
    },
    {
     "title": "RPC Failures Per Operation",
     "type": "graph",
     "gridPos": { "h": 10, "w": 9, "x": 15, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(temporal_request_failure{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ operation }}"
      }
     ]
    },
    {
     "title": "RPC Latencies ($Namespace)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (temporal_namespace, operation, le) (rate(temporal_request_latency_bucket{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m])))",
       "legendFormat": "{{ temporal_namespace }} - {{ operation }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow Completion",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(temporal_workflow_completed{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum(rate(temporal_workflow_failed{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "failed"
      },
      {
       "expr": "sum(rate(temporal_workflow_canceled{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "canceled"
      },
      {
       "expr": "sum(rate(temporal_workflow_continue_as_new{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "continued_as_new"
      }
     ]
    },
    {
     "title": "Workflow End-To-End Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_endtoend_latency_bucket{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m])) by (temporal_namespace, workflow_type, le))",
       "legendFormat": "{{ temporal_namespace }} - {{ workflow_type }}"
      }
     ]
    },
    {
     "title": "Workflow Success By Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace, workflow_type) (rate(temporal_workflow_completed{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ temporal_namespace }} - {{ workflow_type }}"
      }
     ]
    },
    {
     "title": "Workflow Failures By Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace, workflow_type) (rate(temporal_workflow_failed{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ temporal_namespace }} - {{ workflow_type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Workflow Task Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow Task Throughput By WorkflowType",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace, workflow_type) (rate(temporal_workflow_task_queue_poll_succeed{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ temporal_namespace }} - {{ workflow_type }}"
      }
     ]
    },
    {
     "title": "Workflow Task Throughput By temporal_namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace) (rate(temporal_workflow_task_queue_poll_succeed{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ temporal_namespace }}"
      }
     ]
    },
    {
     "title": "Empty Polls",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace) (rate(temporal_workflow_task_queue_poll_empty{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "Empty Poll - {{ temporal_namespace }}"
      }
     ]
    },
    {
     "title": "Workflow Task Backlog By temporal_namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_schedule_to_start_latency_bucket{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m])) by (temporal_namespace, le))",
       "legendFormat": "{{ temporal_namespace }}"
      }
     ]
    },
    {
     "title": "Workflow Task Backlog By Workflow Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_schedule_to_start_latency_bucket{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m])) by (temporal_namespace, workflow_type, le))",
       "legendFormat": "{{ temporal_namespace }} -- {{ workflow_type }}"
      }
     ]
    },
    {
     "title": "Workflow Task Failed By temporal_namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace) (rate(temporal_workflow_task_execution_failed{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ temporal_namespace }}"
      }
     ]
    },
    {
     "title": "Workflow Task Failed By temporal_namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace, workflow_type) (rate(temporal_workflow_task_execution_failed{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ temporal_namespace }} -- {{ workflow_type }}"
      }
     ]
    },
    {
     "title": "Workflow Task Execution Latency By temporal_namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_execution_latency_bucket{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m])) by (temporal_namespace, le))",
       "legendFormat": "{{ temporal_namespace }}"
      }
     ]
    },
    {
     "title": "Workflow Task Execution Latency By Workflow Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_execution_latency_bucket{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m])) by (temporal_namespace, workflow_type, le))",
       "legendFormat": "{{ temporal_namespace }} -- {{ workflow_type }}"
      }
     ]
    },
    {
     "title": "Workflow Task Replay Latency By temporal_namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_replay_latency_bucket{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m])) by (temporal_namespace, le))",
       "legendFormat": "{{ temporal_namespace }}"
      }
     ]
    },
    {
     "title": "Workflow Task Replay Latency By Workflow Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_workflow_task_replay_latency_bucket{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m])) by (temporal_namespace, workflow_type, le))",
       "legendFormat": "{{ temporal_namespace }} -- {{ workflow_type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Activities",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Activity Throughput By temporal_namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace) (rate(temporal_activity_execution_latency_count{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m]))"
      }
     ]
    },
    {
     "title": "Activity Throughput By Activity Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace, activity_type) (rate(temporal_activity_execution_latency_count{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ temporal_namespace }} - {{ activity_type }}"
      }
     ]
    },
    {
     "title": "Failed Activity by Type",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace, activity_type) (rate(temporal_activity_execution_failed{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ temporal_namespace }} - {{ activity_type }}"
      }
     ]
    },
    {
     "title": "Activity Execution Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_execution_latency_bucket{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m])) by (temporal_namespace, activity_type, le))",
       "legendFormat": "{{ temporal_namespace }} - {{ activity_type }}"
      }
     ]
    },
    {
     "title": "Activity End-To-End Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_endtoend_latency_bucket{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m])) by (temporal_namespace, activity_type, le))"
      }
     ]
    }
   ]
  },
  {
   "title": "Activity Task Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Empty Activity Polls By temporal_namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace) (rate(temporal_activity_poll_no_task{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ temporal_namespace }}"
      }
     ]
    },
    {
     "title": "Activity Task Backlog By temporal_namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "dtdurationms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_schedule_to_start_latency_bucket{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m])) by (temporal_namespace, le))"
      }
     ]
    },
    {
     "title": "Activity Task Backlog By Activity Type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "dtdurationms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(temporal_activity_schedule_to_start_latency_bucket{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m])) by (temporal_namespace, activity_type, le))",
       "legendFormat": "{{ temporal_namespace }} - {{ activity_type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sticky Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sticky Cache Hit",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace) (rate(temporal_sticky_cache_hit{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ temporal_namespace }}"
      }
     ]
    },
    {
     "title": "Sticky Cache Miss",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 9, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace) (rate(temporal_sticky_cache_miss{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ temporal_namespace  }}"
      }
     ]
    },
    {
     "title": "Sticky Cache Forced Eviction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace) (rate(temporal_sticky_cache_total_forced_eviction{cluster=\"$cluster\", temporal_namespace=~\"$Namespace\"}[5m]))",
       "legendFormat": "{{ temporal_namespace  }}"
      }
     ]
    },
    {
     "title": "Sticky Cache Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace) (temporal_sticky_cache_size{cluster=\"$cluster\"})",
       "legendFormat": "{{ temporal_namespace }}"
      }
     ]
    }
   ]
  }
 ]
}