{
 "title": "Temporal",
 "description": "Dashboard for Background Checks Demo",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(service_requests,cluster)"
    }
   },
   {
    "name": "Service",
    "query": "frontend,history,matching,worker"
   },
   { "name": "Client", "query": "frontend,history,matching" }
  ]
 },
 "panels": [
  { "title": "Temporal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Availability (Based on Frontend Calls)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (sum(rate(service_errors[2m]) OR on() vector(0)) / sum(rate(service_requests[2m])) * 100)",
     "legendFormat": "availability"
    }
   ]
  },
  {
   "title": "Persistence Availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (sum (rate(persistence_errors[2m]) OR on() vector(0)) /sum (rate(persistence_requests[2m])) * 100)",
     "legendFormat": "availability"
    }
   ]
  },
  {
   "title": "External Events",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(service_requests{operation=~\"StartWorkflowExecution|SignalWorkflowExecution|SignalWithStartWorkflowExecution\"}[2m]))"
    }
   ]
  },
  {
   "title": "Workflow Tasks",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(service_requests{ operation=\"AddWorkflowTask\"}[2m]))",
     "legendFormat": "Scheduled"
    },
    {
     "expr": "sum(rate(service_requests{ operation=\"RecordWorkflowTaskStarted\"}[2m]))",
     "legendFormat": "Started"
    },
    {
     "expr": "sum(rate(service_requests{ operation=\"RespondWorkflowTaskCompleted\"}[2m]))",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(rate(service_requests{ operation=\"RespondWorkflowTaskFailed\"}[2m]))",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(rate(schedule_to_start_timeout{ operation=\"TimerActiveTaskWorkflowTimeout\"}[2m]))",
     "legendFormat": "Sticky Task Queue Timeout"
    },
    {
     "expr": "sum(rate(start_to_close_timeout{ operation=\"TimerActiveTaskWorkflowTimeout\"}[2m]))",
     "legendFormat": "Workflow Task Timeout"
    }
   ]
  },
  {
   "title": "Activities",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(service_requests{operation=\"AddActivityTask\"}[2m]))",
     "legendFormat": "Scheduled"
    },
    {
     "expr": "sum(rate(service_requests{operation=\"RecordActivityTaskStarted\"}[2m]))",
     "legendFormat": "Started"
    },
    {
     "expr": "sum(rate(service_requests{operation=~\"RespondActivityTaskCompleted|RespondActivityTaskFailed|RespondActivityTaskCanceled\"}[2m]))",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Pollers",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "Shard Rebalancing",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(membership_changed_count[2m]))",
     "legendFormat": "membership_changed"
    },
    {
     "expr": "sum(rate(sharditem_created_count[2m]))",
     "legendFormat": "shard_item_created"
    },
    {
     "expr": "sum(rate(sharditem_removed_count[2m]))",
     "legendFormat": "shard_item_removed"
    },
    {
     "expr": "sum(rate(shard_closed_count[2m]))",
     "legendFormat": "shard_closed"
    }
   ]
  },
  {
   "title": "Shard Distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "numshards_gauge", "legendFormat": "{{ kubernetes_pod_name }}" }
   ]
  },
  {
   "title": "Restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (temporal_service_type) (restarts)",
     "legendFormat": "{{ temporal_service_type }}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "num_goroutines", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Memory Allocated",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "memory_allocated", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Memory Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "memory_heap", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "memory_stack", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "GC Counter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (rate(memory_num_gc[5m]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC Pause",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(memory_gc_pause_ms_bucket[5m])) by (kubernetes_pod_name, le))",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "State Transition",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(state_transition_count_count[1m]))",
     "legendFormat": "state transition"
    },
    {
     "expr": "sum(rate(sharditem_created_count[1m]))",
     "legendFormat": "shard_item_created"
    },
    {
     "expr": "sum(rate(sharditem_removed_count[2m]))",
     "legendFormat": "shard_item_removed"
    },
    {
     "expr": "sum(rate(shard_closed_count[2m]))",
     "legendFormat": "shard_closed"
    }
   ]
  },
  {
   "title": "Workflow Completion Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow Completion Overview",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(workflow_success{ operation=\"CompletionStats\"}[5m]))",
       "legendFormat": "success"
      },
      {
       "expr": "sum(rate(workflow_failed{ operation=\"CompletionStats\"}[5m]))",
       "legendFormat": "failed"
      },
      {
       "expr": "sum(rate(workflow_timeout{ operation=\"CompletionStats\"}[5m]))",
       "legendFormat": "timedout"
      },
      {
       "expr": "sum(rate(workflow_terminate{ operation=\"CompletionStats\"}[5m]))",
       "legendFormat": "terminate"
      },
      {
       "expr": "sum(rate(workflow_cancel{ operation=\"CompletionStats\"}[5m]))",
       "legendFormat": "cancelled"
      }
     ]
    },
    {
     "title": "Workflow Success By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace) (rate(workflow_success{ operation=\"CompletionStats\"}[5m]))",
       "legendFormat": "{{ temporal_namespace }} "
      }
     ]
    },
    {
     "title": "Workflow Failed By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace) (rate(workflow_failed{ operation=\"CompletionStats\"}[5m]))",
       "legendFormat": "{{ temporal_namespace }} "
      }
     ]
    },
    {
     "title": "Workflow Timedout By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace) (rate(workflow_timeout{ operation=\"CompletionStats\"}[5m]))",
       "legendFormat": "{{ temporal_namespace }} "
      }
     ]
    },
    {
     "title": "Workflow Terminate By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace) (rate(workflow_terminate{ operation=\"CompletionStats\"}[5m]))",
       "legendFormat": "{{ temporal_namespace }} "
      }
     ]
    },
    {
     "title": "Workflow Cancelled By Namespace",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (temporal_namespace) (rate(workflow_cancel{ operation=\"CompletionStats\"}[5m]))",
       "legendFormat": "{{ temporal_namespace }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Overview - $Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service RequestsVs Errors ($Service)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(service_requests[5m]))",
       "legendFormat": "requests"
      },
      { "expr": "sum (rate(service_errors[5m]))", "legendFormat": "errors" }
     ]
    },
    {
     "title": "Service Requests Per Operation ($Service)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(service_requests[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Service Errors Break Down ($Service)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(service_errors_entity_not_found[5m]) OR on() vector(0))",
       "legendFormat": "Entity Not Found"
      },
      {
       "expr": "sum(rate(service_errors_execution_already_started[5m]) OR on() vector(0))",
       "legendFormat": "Execution Already Started"
      },
      {
       "expr": "sum(rate(service_errors_resource_exhausted[5m]) OR on() vector(0))",
       "legendFormat": "Resource Exhausted"
      }
     ]
    },
    {
     "title": "Service Errors By Operation ($Service)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(service_errors[5m]))"
      }
     ]
    },
    {
     "title": "Service Latency ($Service)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(service_latency_bucket[5m])) by (operation, le))",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Persistence - $Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Persistence Requests Vs Errors ($Service)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (rate(persistence_requests[5m]) OR on() vector(0))",
       "legendFormat": "requests"
      },
      {
       "expr": "sum (rate(persistence_errors[5m]) OR on() vector(0))",
       "legendFormat": "errors"
      }
     ]
    },
    {
     "title": "Persistence Requests Per Operation ($Service)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " sum by (operation) (rate(persistence_requests[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Persistence Errors By Operation ($Service)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(persistence_errors[5m]))"
      }
     ]
    },
    {
     "title": "Persistence Latency ($Service)",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(persistence_latency_bucket[1m])) by (operation, le))",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Client - $Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Vs Errors ($Service -> $Client)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum(rate(client_requests[5m]))", "legendFormat": "requests" },
      { "expr": "sum(rate(client_errors[5m]))", "legendFormat": "errors" }
     ]
    },
    {
     "title": "Client Requests Per Operation ($Service -> $Client)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 9, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(client_requests[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Errors By Operation ($Service -> $Client)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (operation) (rate(client_errors[5m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Client Latency ($Service -> $Client)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(client_latency_bucket[5m])) by (operation, le))",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  }
 ]
}